# StaticBAC Utility Tool Configuration

utility:
  output_dir: ./Output


static_bac:
  folder: ../StaticBAC
  # If it is null, the algorithm search a executable on static-bac folder
  executable: null

models:
  gpt2:
    name: gpt2
    source: HUGGING_FACE
    quantized: false
    inference: MEDIAWIKI
  roBERTa:
    name: textattack/roberta-base-SST-2
    source: HUGGING_FACE
    quantized: false
    inference: STS2
  google-t5:
    name: t5-base
    source: HUGGING_FACE
    quantized: false
    inference: STS2_SEQ2SEQ
  inception-v3:
    name: inception_v3
    source: TORCHVISION
    quantized: true
    weights: Inception_V3_QuantizedWeights.IMAGENET1K_FBGEMM_V1
    inference: IMAGENET
  mobilenet-v3:
    name: mobilenet_v3_large
    source: TORCHVISION
    quantized: true
    weights: MobileNet_V3_Large_QuantizedWeights.IMAGENET1K_QNNPACK_V1
    inference: IMAGENET
  vgg-19:
    name: vgg19
    source: TORCHVISION
    quantized: false
    weights: VGG19_Weights.IMAGENET1K_V1
    inference: IMAGENET
  swin-v2-b:
    name: swin_v2_b
    source: TORCHVISION
    quantized: false
    weights: Swin_V2_B_Weights.IMAGENET1K_V1
    inference: IMAGENET
  # Already tested
  bert:
    name: textattack/bert-base-uncased-SST-2
    source: HUGGING_FACE
    quantized: false
    inference: STS2
  gpt:
    name: openai-gpt
    source: HUGGING_FACE
    quantized: false
    inference: MEDIAWIKI
  resnet50:
    name: resnet50
    source: TORCHVISION
    quantized: false
    weights: ResNet50_Weights.IMAGENET1K_V2
    inference: IMAGENET
  efficientnet-b0:
    name: efficientnet_b0
    source: TORCHVISION
    quantized: false
    weights: EfficientNet_B0_Weights.IMAGENET1K_V1
    inference: IMAGENET
  vit-b-16:
    name: vit_b_16
    source: TORCHVISION
    quantized: false
    weights: ViT_B_16_Weights.IMAGENET1K_V1
    inference: IMAGENET

dataset:
  image_net: ../Datasets/imagenet_validation/